Script started on 2019-09-30 09:48:56+0200
bash-4.4$ openstack stack create -e city-fra1.yaml -t lab.yaml test
ERROR: Internal Error
bash-4.4$ openstack --debug stack create -e city-fra1.yaml -t lab.yaml test 2>&1  | grep -i decode
RESP BODY: {"explanation": "The server could not comply with the request since it is either malformed or otherwise incorrect.", "code": 400, "error": {"traceback": null, "type": "UnicodeDecodeError"}, "title": "Bad Request"}
bash-4.4$ exit

Script done on 2019-09-30 09:49:17+0200
