Script started on 2019-09-30 16:25:10+0200
bash-4.4$ openstack quota show | grep router
| routers                 | 500                                                                                                                                                                                                   |
bash-4.4$ 1openstack quota show | grep router      sune  bnet
| subnet_pools            | -1                                                                                                                                                                                                    |
| subnets                 | 500                                                                                                                                                                                                   |
bash-4.4$ openstack quota show | grep subnet      network
| networks                | 500                                                                                                                                                                                                   |
bash-4.4$ openstack quota show | grep network       port
| ports                   | 1000                                                                                                                                                                                                  |
bash-4.4$ exit

Script done on 2019-09-30 16:25:53+0200
